// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnHaHcfIoQmUAU1wuRxVCkvP96bTnDJiQ',
    appId: '1:197933192727:web:8c65779b22dafd5cfaee52',
    messagingSenderId: '197933192727',
    projectId: 'alumni-connect-b4269a',
    authDomain: 'alumni-connect-b4269a.firebaseapp.com',
    databaseURL: 'https://alumni-connect-b4269a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alumni-connect-b4269a.appspot.com',
    measurementId: 'G-T1Y7GREVHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASBMH635IHid_x5tCq2Vfg0g4gfScU7s4',
    appId: '1:197933192727:android:36c8476509be7d85faee52',
    messagingSenderId: '197933192727',
    projectId: 'alumni-connect-b4269a',
    databaseURL: 'https://alumni-connect-b4269a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alumni-connect-b4269a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5PWw2IX2i7MR0pfhqLLbnZOiK1tfY1hY',
    appId: '1:197933192727:ios:27f0fd1b17b4709efaee52',
    messagingSenderId: '197933192727',
    projectId: 'alumni-connect-b4269a',
    databaseURL: 'https://alumni-connect-b4269a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alumni-connect-b4269a.appspot.com',
    iosBundleId: 'com.smvicre.alumni.alumniconnect',
  );

}