name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Dart SDK
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      # Set up Flutter SDK
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Verify formatting (optional)
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze
        continue-on-error: true  # Allow analysis to fail

      # Run tests
      - name: Run tests
        run: flutter test
